#!/bin/bash


if [ $# -lt 1 ]; then

   echo usage: 3drimc_init nstates
   exit

fi


rm -Rf states/*
cp -R 0 states


for((i=1;i<=$1;i++))
do
   3drimc_mix 3drimc_move.prm states/0  states/0$i 100
done
