#!/bin/bash

if [ $# -lt 1 ]; then
  echo 'usage: 3drimc_run system.rism'
  exit
fi

nam=$(echo $1 | gawk -F. '{print $1}')
ext=$(echo $1 | gawk -F. '{print $2}')

if [ $ext == 'rismx' ]; then
   cat $1 | gawk '{ print $1" "$2" "$3" "$4" "$5" "$6}' > $nam.rism
fi


K='"'
cp parameters.prm $nam.prm
echo SoluteStructureFile=$K$nam.rism$K';' >> $nam.prm

multiGridMain $nam.prm
calculateFreeEnergySimple ${nam}_in_water_  | tee SFE.dat

cat SFE.dat | grep HNC | gawk '{print $2}' > HNC.dat
cat SFE.dat | grep VUA | gawk '{print $2}' > V.dat


